export const data = {
	productSelect: {
		reviews: {
			reviewsRating: {
				count: 52,
				rating: 4.81,
			},
			topics: [
				{
					topicId: 7271061,
					title: "robe",
					total: 12,
					similiarity: 0,
				},
				{
					topicId: 2825994,
					title: "weight",
					total: 11,
					similiarity: 0,
				},
				{
					topicId: 3219366,
					title: "shoulders",
					total: 7,
					similiarity: 0,
				},
				{
					topicId: 3120490,
					title: "neck",
					total: 4,
					similiarity: 0.11111111111111116,
				},
				{
					topicId: 3184092,
					title: "relaxation",
					total: 3,
					similiarity: 0,
				},
				{
					topicId: 7277397,
					title: "collar",
					total: 3,
					similiarity: 0.19999999999999996,
				},
				{
					topicId: 2825978,
					title: "experience",
					total: 2,
					similiarity: 0.30000000000000004,
				},
				{
					topicId: 2826007,
					title: "part",
					total: 2,
					similiarity: 0.16666666666666663,
				},
				{
					topicId: 2882311,
					title: "packaging",
					total: 2,
					similiarity: 0.11111111111111116,
				},
				{
					topicId: 6821700,
					title: "tension",
					total: 2,
					similiarity: 0.11111111111111116,
				},
			],
			reviews: [
				{
					id: 114328203,
					verified: true,
					reviewRating: 5,
					reviewDate: "08/03/2023",
					reviewTitle: "Weighted robe",
					reviewMessage: "This was a gift comes beautifully packaged",
					author: "Heather S.",
					avatar: "https://www.gravatar.com/avatar/0a699e9562eece3059f3ddb6d6ccaf79?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8MTE0MzI4MjAz0",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 114214676,
					verified: true,
					reviewRating: 5,
					reviewDate: "08/02/2023",
					reviewTitle: "The robe of my dreams",
					reviewMessage:
						"After trying the iced sheets, the weighted blanket, the pillow, and the sleep mask, I figured I better get the robe too. It’s so soft and cozy and I love having the weight on my shoulders! Already looking forward to my next hush purchase. Please sponsor me, I’m obsessed with your products😂",
					author: "Maddy C.",
					avatar: "https://www.gravatar.com/avatar/4a4d87cb86071071973787144d580055?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8MTE0MjE0Njc20",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},

				{
					id: 96214871,
					verified: false,
					reviewRating: 5,
					reviewDate: "02/12/2023",
					reviewTitle: "Amazing!",
					reviewMessage: "This robe is legit awesome i can feel the relief when i wear it ",
					author: "Alan",
					avatar: "https://www.gravatar.com/avatar/7fdaec8cd95b6af47364867b7a3d9ba7?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "3",
						},
						{
							message: "Overall Quality",
							value: "4",
						},
						{
							message: "Comfort",
							value: "4",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTYyMTQ4NzE1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 95324101,
					verified: true,
					reviewRating: 5,
					reviewDate: "02/05/2023",
					reviewTitle: "Hush Weighted Robe",
					reviewMessage:
						"After receiving my Hush weighted robe, I waited until after I worked out at the gym...specifically my upper body workout... to try it out! As soon as I felt the plush material, relaxation began to set in! Then the usual aches and shoulder stiffness intense workouts cause were relieved as the weighted collar assisted in relaxing my shoulders as the workout tends to bring my shoulders up (due to stiffness)!\r\nBrilliant product!",
					author: "Angela J.",
					avatar: "https://www.gravatar.com/avatar/ec11490434a0867064b6812dcad398d8?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTUzMjQxMDE1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 94443591,
					verified: true,
					reviewRating: 5,
					reviewDate: "01/29/2023",
					reviewTitle: "Hush weighted robe ",
					reviewMessage:
						"Awesome 🤩 it takes a bit to get used to the weight but it feels awesome afterwards. When I wear it at night just for relaxing before bedtime, I fall asleep 😴 almost instantly. Love it 😍",
					author: "Sylvie V.",
					avatar: "https://www.gravatar.com/avatar/6fe42fcfa3ce149e9f4f859c4bb83b3e?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTQ0NDM1OTE1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 94194169,
					verified: true,
					reviewRating: 5,
					reviewDate: "01/27/2023",
					reviewTitle: "Luxury",
					reviewMessage:
						"I just got mine today, and I was pleasantly surprised with the look and feel of it once I open the box, it has a very luxurious spa feel to it. I got the S/M size and I feel maybe it's just a bit too big and long for me, I think you should have a separate size.",
					author: "Shiva",
					avatar: "https://www.gravatar.com/avatar/bf394bf73d9e452e941d77abd724b6c2?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "3",
						},
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTQxOTQxNjk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 93909485,
					verified: false,
					reviewRating: 5,
					reviewDate: "01/20/2023",
					reviewTitle: "Luxurious Hush robe",
					reviewMessage:
						"Excellent experience. I gave 2 of these LUSH weighted robes as Christmas gifts this year and wished I would have bought one for myself! SOOOOOOOO soft.",
					author: "Lori M.",
					avatar: "https://www.gravatar.com/avatar/717d85fced18fe0b841efc7f3c0fd7b7?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "5",
						},
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTM5MDk0ODU1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 93764459,
					verified: true,
					reviewRating: 4,
					reviewDate: "01/18/2023",
					reviewTitle: "Very nice robe",
					reviewMessage:
						"The robe is very soft, much nicer than my previous. I knocked off a star as I personally haven’t liked using it with the weight. I find it bulky and uncomfortable as it limits your neck movements when sitting on the couch for instance. I have just been using it without the weight so it’s nice that it can be removed easily.",
					author: "Colton W.",
					avatar: "https://www.gravatar.com/avatar/51cf72fb44b9861ce476e818f2540983?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTM3NjQ0NTk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 91464409,
					verified: true,
					reviewRating: 5,
					reviewDate: "12/21/2022",
					reviewTitle: "Best Robe Ever",
					reviewMessage:
						"I think this is my favourite Hush product and I have lots. So soft and comfy. Just love it!!!\r\n",
					author: "Jennifer A.",
					avatar: "https://www.gravatar.com/avatar/79b7f9d48215bcd40723c6918f594050?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "5",
						},
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTE0NjQ0MDk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 91329844,
					verified: true,
					reviewRating: 5,
					reviewDate: "12/18/2022",
					reviewTitle: "Luxury robe! ",
					reviewMessage:
						"Great! Bought one for my mom and she loves how it’s weighted on the shoulders. Very relaxing after a long day.",
					author: "Brooke H.",
					avatar: "https://www.gravatar.com/avatar/8cd3ab30f145f71816f363c67b399b14?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTEzMjk4NDQ1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 91329779,
					verified: true,
					reviewRating: 5,
					reviewDate: "12/18/2022",
					reviewTitle: "Favourite robe",
					reviewMessage: "It’s just what a robe feels like at a luxury spa!",
					author: "Brooke H.",
					avatar: "https://www.gravatar.com/avatar/8cd3ab30f145f71816f363c67b399b14?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTEzMjk3Nzk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 90290717,
					verified: false,
					reviewRating: 5,
					reviewDate: "11/24/2022",
					reviewTitle: "Absolutely phenomenal",
					reviewMessage:
						"Definitely the robe to wear this is unbelievably soft and the weighted aspect is very relaxing!",
					author: "Chris",
					avatar: "https://www.gravatar.com/avatar/462ef88d4df35217185ea5534c1b1380?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "5",
						},
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTAyOTA3MTc1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 90041729,
					verified: true,
					reviewRating: 5,
					reviewDate: "11/18/2022",
					reviewTitle: "Hushhhhh… I’m relaxing!!!! ",
					reviewMessage:
						"I LOVE m’y HUSH Robe!! Not just when getting out of the bath or shower but I wear it as soon as I come home! It’s so relaxing and the weight around my shoulders feels like a BIG hug!! It’s very luxurious & warm & soothinggggg!!!",
					author: "Jackie R.",
					avatar: "https://www.gravatar.com/avatar/6c4873c2427629a2f0f69626d240425f?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [
						"https://s3.us-west-2.amazonaws.com/stamped.io/uploads/videos/3eeba175282318724ef9c1bee2be070b.mp4",
					],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8OTAwNDE3Mjk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 89300594,
					verified: true,
					reviewRating: 5,
					reviewDate: "11/07/2022",
					reviewTitle: "Soft and comfy",
					reviewMessage: "Very awesome. Love it",
					author: "Peter N.",
					avatar: "https://www.gravatar.com/avatar/b8858a38b5078be8bb336784a0b0d171?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8ODkzMDA1OTQ1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 88959368,
					verified: false,
					reviewRating: 5,
					reviewDate: "11/01/2022",
					reviewTitle: "Luxurious Comfort",
					reviewMessage:
						"Amazingly surprised by the packaging, then experience of relaxation from weighted collar. Felt immediate shoulder, neck tension release. Kudos to adding weight to neck area.",
					author: "Iris",
					avatar: "https://www.gravatar.com/avatar/be4379c383d70c967d10d52be7427380?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8ODg5NTkzNjg1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 88361992,
					verified: true,
					reviewRating: 5,
					reviewDate: "10/23/2022",
					reviewTitle: "Amazing!!!!!",
					reviewMessage:
						"It’s super soft and after a long day as soon as I put it on I can feel my shoulders soften, my breathing slowing and relaxation kicking in.",
					author: "Andrew R.",
					avatar: "https://www.gravatar.com/avatar/c3e6f08dbff5030a79b450656780f0be?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8ODgzNjE5OTI1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 88361056,
					verified: true,
					reviewRating: 5,
					reviewDate: "10/23/2022",
					reviewTitle: "Very comfortable ",
					reviewMessage: "Excellent robe, the weight on the neck is very relaxing. 👍&#55356;",
					author: "Mario B.",
					avatar: "https://www.gravatar.com/avatar/bc8971b56c24ad626fd27fd3075ad6f5?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8ODgzNjEwNTY1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 87285042,
					verified: true,
					reviewRating: 5,
					reviewDate: "09/24/2022",
					reviewTitle: "Hush robe",
					reviewMessage:
						"Ii removed it from it’s package and it was the softest robe I’ve ever felt. Instantly threw it on!!! Right away I could feel the weighted neck & shoulders release my tension!!! \r\nBest cuddles ever 🥰",
					author: "Colleen D.",
					avatar: "https://www.gravatar.com/avatar/81873ded2180bb6659ec34fefb18cd68?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8ODcyODUwNDI1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 87248357,
					verified: true,
					reviewRating: 5,
					reviewDate: "09/23/2022",
					reviewTitle: "Honest review here guys",
					reviewMessage:
						"I never expected the weights inside the robe to have such a relaxing effect. I used to have a robe which i would put on after shower to chill at my computer but truth to be told with this one I just can’t do that or I just feel like sleeping. It is so much relaxing that it has become an inconvenience for me. Im leaving 5 stars because its fully serving its purpose but it is so much that im barely using it. ( you can always remove the weights but im super lazy) Great job hush!",
					author: "jimmy c.",
					avatar: "https://www.gravatar.com/avatar/fbc087438b0c67263f610b6d8e89679d?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [
						"https://cdn.stamped.io/uploads/photos/85144_7075738615994_f3d99e28_846a_4150_906c_c879e47afedd.jpg",
					],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8ODcyNDgzNTc1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 87042470,
					verified: true,
					reviewRating: 5,
					reviewDate: "09/17/2022",
					reviewTitle: "Wow",
					reviewMessage:
						"The sheets and pillow cases really do keep a comfortable temperature through the night. They feel so soft to the touch. If you are a hot sleeper these are definitely worth the money.",
					author: "Natalie L.",
					avatar: "https://www.gravatar.com/avatar/24ac45ad75ea551ac280a8df93f1dfe8?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [
						"https://cdn.stamped.io/uploads/photos/85144_7075738615994_2b0fcc88_2f5f_46d6_94fe_aa9ae6866cb4.jpg",
					],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8ODcwNDI0NzA1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 85118606,
					verified: true,
					reviewRating: 5,
					reviewDate: "08/11/2022",
					reviewTitle: "Softest robe",
					reviewMessage:
						"Brought it for my girlfriend and she really loves it, now I'm planning on getting myself one once I have enough money again",
					author: "Phonesavanh S.",
					avatar: "https://www.gravatar.com/avatar/0bc48212bee9d434c39c1db8a308f6d6?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MjQxfHJ8ODUxMTg2MDY1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85241_6869641691218.jpg?tr=h-180&v=1678830468",
					},
				},
				{
					id: 84890815,
					verified: true,
					reviewRating: 5,
					reviewDate: "08/06/2022",
					reviewTitle: "Robe de chambre ultra douce et apaisante",
					reviewMessage:
						"J'adore ma nouvelle robe de chambre ultra douce et apaisante. La première fois que je l'ai porté je me suis endormie! Faites vous ce cadeau!",
					author: "Cynthia M.",
					avatar: "https://www.gravatar.com/avatar/6d4e097bf16c1b62884700150ca685a4?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 1,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8ODQ4OTA4MTU1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 84253648,
					verified: false,
					reviewRating: 5,
					reviewDate: "07/26/2022",
					reviewTitle: "Luxury",
					reviewMessage:
						"The bathrobe is very soft and it looks amazing. 3 pounds on the shoulder is very comfortable",
					author: "Isabelle",
					avatar: "https://www.gravatar.com/avatar/33527ef45ce73873a3eb15298a4e67ee?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "5",
						},
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8ODQyNTM2NDg1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 76722578,
					verified: true,
					reviewRating: 5,
					reviewDate: "06/23/2022",
					reviewTitle: "Bougie robe",
					reviewMessage: "Plush and comfortable. Feels like a deluxe spa robe. ",
					author: "BRANDON W.",
					avatar: "https://www.gravatar.com/avatar/155c829c3d28b1a8b5e50d01c8e0e6ae?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzY3MjI1Nzg1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 74593828,
					verified: true,
					reviewRating: 4,
					reviewDate: "06/09/2022",
					reviewTitle: "Love it, wish there were more styles",
					reviewMessage:
						"I very much liked the rob.  i love the weight on the shoulders from how the robe is designed.  \r\n\r\nI do wish there was a different style, in the rob cut but like lesser weighted blanket (or a blanket for one) in the cut of a robe would be cool so the weight would be everywhere spread over the body.",
					author: "Tim S.",
					avatar: "https://www.gravatar.com/avatar/9221ed72a25254ddcc2482f356e0cb8e?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzQ1OTM4Mjg1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 74593827,
					verified: true,
					reviewRating: 4,
					reviewDate: "06/09/2022",
					reviewTitle: "Love it, wish there were more styles",
					reviewMessage:
						"I very much liked the rob.  i love the weight on the shoulders from how the robe is designed.  \r\n\r\nI do wish there was a different style, in the rob cut but like lesser weighted blanket (or a blanket for one) in the cut of a robe would be cool so the weight would be everywhere spread over the body.",
					author: "Tim S.",
					avatar: "https://www.gravatar.com/avatar/9221ed72a25254ddcc2482f356e0cb8e?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzQ1OTM4Mjc1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 74593829,
					verified: true,
					reviewRating: 4,
					reviewDate: "06/09/2022",
					reviewTitle: "Love it, wish there were more styles",
					reviewMessage:
						"I very much liked the rob.  i love the weight on the shoulders from how the robe is designed.  \r\n\r\nI do wish there was a different style, in the rob cut but like lesser weighted blanket (or a blanket for one) in the cut of a robe would be cool so the weight would be everywhere spread over the body.",
					author: "Tim S.",
					avatar: "https://www.gravatar.com/avatar/9221ed72a25254ddcc2482f356e0cb8e?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzQ1OTM4Mjk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 74593821,
					verified: true,
					reviewRating: 4,
					reviewDate: "06/09/2022",
					reviewTitle: "Love it, wish there were more styles",
					reviewMessage:
						"I very much liked the rob.  i love the weight on the shoulders from how the robe is designed.  \r\n\r\nI do wish there was a different style, in the rob cut but like lesser weighted blanket (or a blanket for one) in the cut of a robe would be cool so the weight would be everywhere spread over the body.",
					author: "Tim S.",
					avatar: "https://www.gravatar.com/avatar/9221ed72a25254ddcc2482f356e0cb8e?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzQ1OTM4MjE1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 74593804,
					verified: true,
					reviewRating: 4,
					reviewDate: "06/09/2022",
					reviewTitle: "Love it, wish there were more styles",
					reviewMessage:
						"I very much liked the rob.  i love the weight on the shoulders from how the robe is designed.  \r\n\r\nI do wish there was a different style, in the rob cut but like lesser weighted blanket (or a blanket for one) in the cut of a robe would be cool so the weight would be everywhere spread over the body.",
					author: "Tim S.",
					avatar: "https://www.gravatar.com/avatar/9221ed72a25254ddcc2482f356e0cb8e?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzQ1OTM4MDQ1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 74593803,
					verified: true,
					reviewRating: 4,
					reviewDate: "06/09/2022",
					reviewTitle: "Love it, wish there were more styles",
					reviewMessage:
						"I very much liked the rob.  i love the weight on the shoulders from how the robe is designed.  \r\n\r\nI do wish there was a different style, in the rob cut but like lesser weighted blanket (or a blanket for one) in the cut of a robe would be cool so the weight would be everywhere spread over the body.",
					author: "Tim S.",
					avatar: "https://www.gravatar.com/avatar/9221ed72a25254ddcc2482f356e0cb8e?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzQ1OTM4MDM1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 74519714,
					verified: true,
					reviewRating: 5,
					reviewDate: "06/08/2022",
					reviewTitle: "Robes",
					reviewMessage:
						"Luxurious  and cozy! Had to remove the weights  as they were too heavy. Otherwise enjoying them",
					author: "Pina P.",
					avatar: "https://www.gravatar.com/avatar/88c6f92761a5792d015f23328ca31dd0?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzQ1MTk3MTQ1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 73124273,
					verified: true,
					reviewRating: 4,
					reviewDate: "05/31/2022",
					reviewTitle: "Hush Robe",
					reviewMessage:
						"Robe is very plush and feels great. Weighted portion is not quite what I expected (just a weight around neck/on shoulders) but my wife and I are both enjoying the robes so far. Weight is removable as well which is a good idea.",
					author: "Chad L.",
					avatar: "https://www.gravatar.com/avatar/96ec8072b7a9de3f1ba6cf35975f51e1?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 1,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzMxMjQyNzM1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 72223317,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/21/2022",
					reviewTitle: "So Luxurious!",
					reviewMessage: "Very comfy.  Got one for myself and spouse.  High end hotel quality.",
					author: "Dawn C.",
					avatar: "https://www.gravatar.com/avatar/15ac5a97100bd5d35b53fe134beeb1f4?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzIyMjMzMTc1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 72191649,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/20/2022",
					reviewTitle: "another excellent product ",
					reviewMessage:
						"i can’t get enough of hush and sleep so much better! There is nothing better is getting a big “hug” prior to going to bed. the robe is super soft, washes well and is another example of the fine craftsmanship by Hush. The robe is generously sized   i purchased two robes as wedding gifts for my daughter. looks beautiful on her special day",
					author: "Simone M.",
					avatar: "https://www.gravatar.com/avatar/949c1ce90a6c457bff865f8ce38e9634?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzIxOTE2NDk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 72016143,
					verified: true,
					reviewRating: 4,
					reviewDate: "05/19/2022",
					reviewTitle: "Soft and Comfortable",
					reviewMessage: "It's very soft and comfortable, and the weight helps with anxiety.",
					author: "Olivia W.",
					avatar: "https://www.gravatar.com/avatar/29734f36d38f1e3e23eb4e92f903d737?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzIwMTYxNDM1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71931085,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/18/2022",
					reviewTitle: "Heaven",
					reviewMessage:
						"Robes arrived quickly. Softest robe ever! Bought one for my daughter :) I love my HUSH products!",
					author: "Lorrie C.",
					avatar: "https://www.gravatar.com/avatar/f15f85f0cae73558ce16d1693d1ae894?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzE5MzEwODU1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71826434,
					verified: true,
					reviewRating: 4,
					reviewDate: "05/17/2022",
					reviewTitle: "The hush weighted-robe ",
					reviewMessage: "Overall my experience with this item has been great.",
					author: "Arnold M.",
					avatar: "https://www.gravatar.com/avatar/2c6963435b16de9dab2fe6bfad4e5605?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [
						"https://cdn.stamped.io/uploads/photos/85241_6869641691218_e664ef40_9f1e_475b_8684_eea6a1411617.jpg",
					],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MjQxfHJ8NzE4MjY0MzQ1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85241_6869641691218.jpg?tr=h-180&v=1678830468",
					},
				},
				{
					id: 71698089,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/16/2022",
					reviewTitle: "HuSh Weighted Robe ",
					reviewMessage:
						"Oh My Goodness !  Skirt  is so beautiful, so Soft  and luxurious absolutely wonderful.  The weights  are lIke a hug!  The they relieve the day's stress and encourage relaxation.   I love it !",
					author: "Arlene M.",
					avatar: "https://www.gravatar.com/avatar/07edc63b88ae52dc25b0a8e6d256347b?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzE2OTgwODk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71674089,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/15/2022",
					reviewTitle: "It’s a nice hug",
					reviewMessage:
						"I have a tendency to wear my shoulders up around my ears like they are a pair of earrings. I hold much of my tension in my neck and shoulders. This has been a gentle reminder to relax and let go.  It’s a nice hug in a cozy soft cover.",
					author: "Linda W.",
					avatar: "https://www.gravatar.com/avatar/217972dac5c43ba0272161490ecce054?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 1,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzE2NzQwODk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71639842,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/14/2022",
					reviewTitle: "Skirt ",
					reviewMessage:
						"I don’t have a bad thing to say about this item. Luxurious fabric so soft and cuddly and perfect weight around the collar. Absolutely love this item. ♥️",
					author: "Linda C.",
					avatar: "https://www.gravatar.com/avatar/bbe96529d4239de1aadbc91e5256a839?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzE2Mzk4NDI1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71634466,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/14/2022",
					reviewTitle: "I love my Hush Weighted Robe!",
					reviewMessage:
						"It is so comfortable and soft. The weight is just right for me.  Thank you Hush.",
					author: "Carmen M.",
					avatar: "https://www.gravatar.com/avatar/900280da622e1ef4480d5b5282138a19?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzE2MzQ0NjY1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71628394,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/14/2022",
					reviewTitle: "Mixed emotions ",
					reviewMessage:
						"Absolutely love this robe 😍 it's super soft and comfortable! My mixed emotions come from having a hard time actually wearing it, cause within a half hour it puts me in a deep sleep for about 3 hours every time!!",
					author: "Daniel W.",
					avatar: "https://www.gravatar.com/avatar/ba8343ef72680185899cc9c125d51924?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzE2MjgzOTQ1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71627545,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/14/2022",
					reviewTitle: "Spa like robe ",
					reviewMessage: "Feels like a spa in our bathroom ❤️",
					author: "Katie L.",
					avatar: "https://www.gravatar.com/avatar/8d4f3d0a357e25dbff6407b5ce259bcc?d=mm",
					productVariantName: "Large/XL",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzE2Mjc1NDU1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71553289,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/13/2022",
					reviewTitle: "Obsessed! ",
					reviewMessage:
						"Bought this for my partner and I and we both love it! Perfect weight on the shoulders, it relaxes you right away.",
					author: "Chloe M.",
					avatar: "https://www.gravatar.com/avatar/c7d10bf06b1720dff71ba2edaee18d42?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzE1NTMyODk1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71536934,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/13/2022",
					reviewTitle: "Love  the robe!",
					reviewMessage:
						"So nice and fluffy and still without the “trap the heat” of other robes like this. The weight is amazing on my neck; I think the only way that this robe could improve is to offer colors other than white!",
					author: "Karla C.",
					avatar: "https://www.gravatar.com/avatar/8db3041601c2442517147262b3b2a9cb?d=mm",
					productVariantName: "Large",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzE1MzY5MzQ1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71277215,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/12/2022",
					reviewTitle: "Love my new robe!",
					reviewMessage:
						"After a long day, putting on this robe is amazing and really helps you relax before going to bed.",
					author: "Cindy P.",
					avatar: "https://www.gravatar.com/avatar/b00cc33fcf1425a2b7753261bc7b85f9?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzEyNzcyMTU1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 71270487,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/12/2022",
					reviewTitle: "Best ever ",
					reviewMessage: "Absolutely love it",
					author: "Thomas G.",
					avatar: "https://www.gravatar.com/avatar/8b1e879b63ab3043ed9555a35ccd0873?d=mm",
					productVariantName: "Large",
					productName: "Skirt ",
					reviewOptionsList: [],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzEyNzA0ODc1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 70890965,
					verified: true,
					reviewRating: 5,
					reviewDate: "05/05/2022",
					reviewTitle: "Robe was awesome ",
					reviewMessage: "So comfy and love the weight wanna stay in it all day lol",
					author: "Dwight ",
					avatar: "https://www.gravatar.com/avatar/013c2937e195f8bfda94c0e86b7aa9b1?d=mm",
					productVariantName: "Small/Medium",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "5",
						},
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [
						"https://cdn.stamped.io/uploads/photos/85144_7075738615994_dd06ff8c_9187_451b_be02_6e22ba7481f5.jpg",
					],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 1,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzA4OTA5NjU1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 70364801,
					verified: false,
					reviewRating: 5,
					reviewDate: "04/29/2022",
					reviewTitle: "Great Quality",
					reviewMessage:
						"Good quality robe- fits nice and cozy. The weight feels nice to have around the kneck. Makes you sleepy I find. Would reccomend. ",
					author: "Amanda B.",
					avatar: "https://www.gravatar.com/avatar/d4f4a35290b20d9453e3012abcafbb96?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "5",
						},
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 0,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzAzNjQ4MDE1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 70364772,
					verified: false,
					reviewRating: 5,
					reviewDate: "04/29/2022",
					reviewTitle: "Great Mothers Day Gift",
					reviewMessage:
						"Gave it to my Mom early. She is 64. She LOVES it. Should have taken advantage of the BOGO offer because now I want one. \r\n\r\nps: If you are 5'7-6'0ft tall  get the Medium ",
					author: "Daniel R.",
					avatar: "https://www.gravatar.com/avatar/076bc56c8765e555867cb0225e0fef98?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "5",
						},
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 1,
						reviewVotesDown: 0,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzAzNjQ3NzI1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
				{
					id: 70364723,
					verified: false,
					reviewRating: 5,
					reviewDate: "04/29/2022",
					reviewTitle: "Incredible quality ",
					reviewMessage:
						"I wanted to jump on this the moment I got the text. Arrived in 2 days and the quality is amazing. Feel the power of the weighted part almost right away. Love reading my book with it after a long day. Beautifully packaged. ",
					author: "Sasha T.",
					avatar: "https://www.gravatar.com/avatar/cd523d915155d6686adc3333e03165fc?d=mm",
					productName: "Skirt ",
					reviewOptionsList: [
						{
							message: "Sleep Improvement",
							value: "5",
						},
						{
							message: "Overall Quality",
							value: "5",
						},
						{
							message: "Comfort",
							value: "5",
						},
					],
					reviewUserPhotos: [],
					reviewUserVideos: [],
					popUp: {
						reviewVotesUp: 2,
						reviewVotesDown: 1,
						productUrl: "https://stamped.io/go/d3xOb25lfDg1MTQ0fHJ8NzAzNjQ3MjM1",
						productName: "Skirt ",
						productImage:
							"https://cdn.stamped.io/uploads/productImages/85144_7075738615994.jpg?tr=h-180",
					},
				},
			],
		},
		seo: {
			title: "Skirt  – Hangzhou Gravity",
			description:
				"The robe you didn't know you needed. Until now. The gentle weight around your neck gives you the calming sensation of Hush while looking your best. Check out how it works here.",
		},
		videos: [],
	},
	reviewsData: {
		reviewsV2: {
			readAllLabel: "Read all",
			addReviewLabel: "Add review",
			filterByLabel: "Filter by",
			clearLabel: "Clear",
		},
		customerReviewsLabel: "Customer Reviews",
		loadMoreLabel: "Load More Reviews",
		showLessLabel: "Show Less Reviews",
		writeReviewLabel: "Write a Review",
		optionsFilters: {
			sleep: [
				{
					name: "Sleep Improvement",
					value: "reset",
				},
				{
					name: "4",
					value: "4",
				},
				{
					name: "5",
					value: "5",
				},
			],
			quality: [
				{
					name: "Overall Quality",
					value: "reset",
				},
				{
					name: "4",
					value: "4",
				},
				{
					name: "5",
					value: "5",
				},
			],
			comfort: [
				{
					name: "Comfort",
					value: "reset",
				},
				{
					name: "4",
					value: "4",
				},
				{
					name: "5",
					value: "5",
				},
			],
			sort: [
				{
					name: "Sort",
					value: "reset",
				},
				{
					name: "With Photos",
					value: "withPhotos",
				},
				{
					name: "Most Recent",
					value: "mostRecent",
				},
				{
					name: "Highest Rating",
					value: "highestRating",
				},
				{
					name: "Lowest Rating",
					value: "lowestRating",
				},
				{
					name: "Most Helpful",
					value: "mostHelpful",
				},
			],
		},
		filters: {
			clearBtnLabel: "Clear filters",
			moreBtnLabel: "More Filters",
			filterReviewsLabel: "Filter Reviews",
		},
		noReviewsLabel:
			"No reviews matched the selected criteria. Clear or modify your filter and try again.",
		reviewData: {
			verifiedLabel: "Verified Buyer",
			dataLabel: "Review left",
		},
		header: {
			reviewsLabel: "reviews",
			countLabel: "Based on",
		},
		form: {
			firstName: {
				label: "Name*",
				placeholder: "Enter your name",
			},
			email: {
				label: "Email*",
				placeholder: "john.smith@example.com",
			},
			rating: "Rating*",
			review: {
				label: "How was your overall experience?*",
				placeholder: "",
			},
			reviewTitle: {
				label: "Title of Review*",
				placeholder: "Give your review a title",
			},
			sleepQuality: {
				id: "sleepQuality",
				label:
					"How would you rate the quality of your sleep since you started sleeping with a Hush?",
			},
			productQuality: {
				id: "productQuality",
				label: "How would rate the quality of the products?",
			},
			comfy: {
				id: "comfy",
				label: "How comfy do you find your Hush to be?",
			},
			photos: "Add photos",
			optionalSuffix: "Optional",
			buttonLabel: "Submit",
			successMessage: {
				title: "Thank you for submitting a review!",
				subtitle:
					" Your input is very much appreciated. Share it with your friends so they can enjoy it too!",
				facebook: {
					label: "Facebook",
					href: "",
				},
				twitter: {
					label: "Twitter",
					href: "",
				},
			},
		},
	},
	reviewVariant: "default",
};
